name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1 
      - uses: denolib/setup-deno@v1.1.0
        with:
          deno-version: 0.x
      - run: deno fetch test_server.ts
      - run: deno run -A test.ts
